### ISSUE TITLE
FancyNpcs - API

### ISSUE THREAD

**Issue by Ducki0210** [OliverSchlueter/FancyNpcs#5]
Hello, I did not try your plugin already, it seems really great and I would like to use it.

However, I did not find any API so I would like to request you to add an API with all the creation, get, ... methods and a PlayerNpcInteractEvent :)

I hope you can make it ASAP ty :D

**Comment by OliverSchlueter** [comment]
Hey, nice that you are interested in using the plugin. I will add more API to it shortly and keep you updated in this issue

**Comment by OliverSchlueter** [comment]
@Ducki0210 I have added a buch of API stuff. Check out [Documentation.md](https://github.com/OliverSchlueter/NpcPlugin/blob/main/Documentation.md)

If you have questions feel free to ask them here or on discord (Oliver#6538).

**Comment by Ducki0210** [comment]
I took a look quickly and it seems full, I will try it and ask you if I have an question ! :D

**Comment by Ducki0210** [comment]
Hey, I found the gradle project repository and dependency but not the maven one, is there one ?
Also, I was wondering if there is an option to set multiple lines above the NPC's head ?

or maybe a command like /npc displayName (name) (line) (text) ?

**Comment by OliverSchlueter** [comment]
I'm not too familiar with Maven but it should be something like this:

```maven
<dependency>
    <groupId>de.oliver</groupId>
    <artifactId>NpcPlugin</artifactId>
    <version>1.1.1</version>
    <scope>provided</scope>
</dependency>
```

About the multi line: You would need to use holograms for that. I have planned to integrate my FancyHolograms plugin but I'm currently very busy.

**Comment by Ducki0210** [comment]
Ahh sorry, I hate to ask that much but I am not very good with all the maven and gradle stuff...

**Comment by OliverSchlueter** [comment]
All good, I'm not very good with maven and gradle aswell 👀

**Comment by OliverSchlueter** [comment]
@Ducki0210 do you have any more questions or can I close this issue?
