### ISSUE TITLE
Velocity/Proxy support?

### ISSUE THREAD

**Issue by yourfriendoss** [OliverSchlueter/FancyNpcs#7]
It seems to be missing.

**Comment by OliverSchlueter** [comment]
What exactly is missing? There is already support for "/npc playerCommand <npc> server <server name>". I can add more if you tell me what you need

**Comment by yourfriendoss** [comment]
Okay, oops. I didn't check if that worked, and it seems to work. I found a different issue, for which I'll create a issue now. Thanks for this plugin!
